### ISSUE TITLE
EyeWitness error

### ISSUE THREAD

**Issue by tanujjane** [TypeError/domained#57]
Traceback (most recent call last):
  File "/home/ec2-user/domained/bin/EyeWitness/EyeWitness.py", line 612, in <module>
    duplicate_check(cli_parsed)
  File "/home/ec2-user/domained/bin/EyeWitness/modules/helpers.py", line 309, in duplicate_check
    with open(cli_object.d + "/Requests.csv", 'r') as csv_port_file:
IOError: [Errno 2] No such file or directory: '/home/ec2-user/domained/output/example.io-07-30-19-17-47-EW/Requests.csv'

**Comment by tanujjane** [comment]
![Screenshot 2019-07-30 at 11 33 26 PM](https://user-images.githubusercontent.com/2560768/62153605-91546d00-b322-11e9-9f45-bc32eec278e6.png)

**Comment by tanujjane** [comment]
@cak  please help

**Comment by mzfr** [comment]
We are having quite a few issue with eyewitness. That is the reason for opening issue  #52.

**Comment by tanujjane** [comment]
@mzfr    why don’t you try https://github.com/maaaaz/webscreenshot/

**Comment by mzfr** [comment]
Yes there are multiple tools like that but plan of using aquatone is because that is well developed tool with constant development.

**Comment by tanujjane** [comment]
@mzfr Great, it's a great tool. will wait for the update.
