### ISSUE TITLE
Error Attempting to screenshot

### ISSUE THREAD

**Issue by tanujjane** [TypeError/domained#61]
Attempting to screenshot https://.example.com
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/encodings/idna.py", line 165, in encode
    raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ec2-user/domained/bin/EyeWitness/EyeWitness.py", line 303, in worker_thread
    http_object.resolved = resolve_host(http_object.remote_system)
  File "/home/ec2-user/domained/bin/EyeWitness/modules/helpers.py", line 293, in resolve_host
    resolved = socket.gethostbyname(system)
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Finished in 8636.717457056046 seconds

Traceback (most recent call last):
  File "domained.py", line 463, in <module>
    options()
  File "domained.py", line 442, in options
    colored("\nAll your subdomain are belong to us", colorama.Fore.BLUE)
NameError: name 'colored' is not defined

**Comment by tanujjane** [comment]
@mzfr  Please help

**Comment by tanujjane** [comment]
Why getting this error?

Attempting to screenshot https://.example.com
Process Process-5:
Traceback (most recent call last):
File "/usr/lib/python3.7/encodings/idna.py", line 165, in encode
raise UnicodeError("label empty or too long")
UnicodeError: label empty or too long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
self.run()
File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
self._target(*self._args, **self._kwargs)
File "/home/ec2-user/domained/bin/EyeWitness/EyeWitness.py", line 303, in worker_thread
http_object.resolved = resolve_host(http_object.remote_system)
File "/home/ec2-user/domained/bin/EyeWitness/modules/helpers.py", line 293, in resolve_host
resolved = socket.gethostbyname(system)
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Finished in 8636.717457056046 seconds

**Comment by ccsplit** [comment]
It's possibly because it is an invalid domain `.example.com`, however, it also appears to be an issue within EyeWitness caused internally within `socket.gethostbyname` because the subdomain portion is not available (`<this portion>.example.com`).

**Comment by tanujjane** [comment]
@ccsplit Yes, you are right this .example.com is an invalid domain and getting this error for all domains. **But how to resolve this issue?**
