### ISSUE TITLE
Enumall Error

### ISSUE THREAD

**Issue by tanujjane** [TypeError/domained#62]
Running Enumall 

Running Command: python /home/ec2-user/domained/bin/domain/enumall.py example.com
Traceback (most recent call last):
  File "/home/ec2-user/domained/bin/domain/enumall.py", line 28, in <module>
    from recon.core import base
  File "/usr/share/recon-ng/recon/core/base.py", line 32
    framework.Framework._spool.write(f"{args[0]}{os.linesep}")
                                                            ^
SyntaxError: invalid syntax

@mzfr  Please help

**Comment by mzfr** [comment]
@tanujjane i think this has to do with your python version. Try to use python 3.7

**Comment by tanujjane** [comment]
@mzfr I did but no effect. still facing same issue.

**Comment by tanujjane** [comment]
@ccsplit  pls help

**Comment by mzfr** [comment]
@tanujjane This is actually a problem with enumall. It isn't updated to support python3. It's still using python2, now when we run the domained tool in python3 it breaks on the `print` statement.

If you want to run it separtely follow [these steps](https://github.com/jhaddix/domain#pre-requisites)
