### ISSUE TITLE
subfinder not found in bin

### ISSUE THREAD

**Issue by n1ghtfox** [TypeError/domained#66]
ubfinder is not currently in your $PATH 

Traceback (most recent call last):
  File "domained.py", line 463, in <module>
    options()
  File "domained.py", line 436, in options
    subfinder()
  File "domained.py", line 245, in subfinder
    if check_gopath("subfinder", "github.com/subfinder/subfinder") and rerun != 1:
  File "domained.py", line 198, in check_gopath
    if os.environ["GOPATH"]:
  File "/usr/lib/python3.7/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'GOPATH'

**Comment by mzfr** [comment]
You need to add `GOPATH` in your environment variables. That variable should point to the location where you've installed go.

**Comment by n1ghtfox** [comment]
it's under /bin ofc and it still doesnt work for some reason..

**Comment by n1ghtfox** [comment]
i had to manually install subfinder under bin folder
